apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deploy
  labels:
    app: hello-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
      tier: frontend
  template:
    metadata:
      labels:
        app: hello-app
        tier: frontend
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
          - containerPort: 8080
